countries = [
    'Afghanistan (AFN)', 'Aland Islands (EUR)', 'Albania (ALL)', 'Algeria (DZD)', 'American Samoa (EUR)',
    'Andorra (EUR)', 'Angola (AOA)', 'Anguilla (XCD)', 'Antarctica (AQD)', 'Antigua and Barbuda (XCD)',
    'Argentina (ARS)', 'Armenia (AMD)', 'Aruba (ANG)', 'Australian (AUD)', 'Austria (EUR)', 'Azerbaijan (AZN)',
    'Bahamas (BSD)', 'Bahrain (BHD)', 'Bangladesh (BDT)', 'Barbados (BBD)', 'Belarus (BYR)', 'Belgium (EUR)',
    'Belize (BZD)', 'Benin (XOF)', 'Bermuda (BMD)', 'Bhutan (INR)', 'Bolivia (BOB)', 'Bosnia and Herzegovina (BAM)',
    'Botswana (BWP)', 'Bouvet Island (NOK)', 'Brazil (BRL)', 'British Indian Ocean Territory (USD)',
    'Brunei Darussalam (BND)',
    'Bulgaria (BGN)', 'Burkina Faso (XOF)', 'Burundi (BIF)', 'Cambodia (KHR)', 'Cameroon (XAF)', 'Canada (CAD)',
    'Cape Verde (CVE)', 'Cayman Islands (KYD)', 'Central African Republic (XAF)', 'Chad (XAF)', 'Chile (CLP)',
    'China (CNY)', 'Christmas Island (AUD)', 'Cocos (Keeling) Islands (AUD)', 'Colombia (COP)', 'Comoros (KMF)',
    'Congo (Kinshasa) (CDF)', 'Congo Republic of the Democratic (XAF)', 'Congo-Brazzaville (CDF)', 'Cook Islands (NZD)',
    'Costa Rica (CRC)', 'Croatia (Hrvatska) (HRK)', 'Cuba (CUP)', 'Cyprus (CYP)', 'Czech Republic (CZK)',
    'Denmark (DKK)', 'Djibouti (DJF)', 'Dominica (XCD)',
    'Dominican Republic (DOP)', 'East Timor (IDR)', 'Ecuador (ECS)', 'Egypt (EGP)', 'El Salvador (SVC)',
    'Equatorial Guinea (XAF)', 'Eritrea (ETB)', 'Estonia (EEK)', 'Ethiopia (ETB)', 'Falkland Islands (Malvinas) (FKP)',
    'Faroe Islands (DKK)', 'Fiji (FJD)', 'Finland (EUR)', 'France (EUR)', 'French Guiana (EUR)',
    'French Polynesia (XPF)', 'French Southern Territories (EUR)', 'Gabon (XAF)', 'Gambia (GMD)', 'Georgia (GEL)',
    'Germany (EUR)', 'Ghana (GHS)', 'Gibraltar (GIP)', 'Greece (EUR)', 'Greenland (DKK)', 'Grenada (XCD)',
    'Guadeloupe (EUR)', 'Guam (USD)', 'Guatemala (GTQ)', 'Guernsey (GGP)', 'Guinea (GNF)', 'Guinea-Bissau (XOF)',
    'Guyana (GYD)',
    'Haiti (HTG)', 'Heard and Mc Donald Islands (AUD)', 'Honduras (HNL)', 'Hong Kong (HKD)', 'Hungary (HUF)',
    'Iceland (ISK)', 'India (INR)', 'Indonesia (IDR)', 'Iran (Islamic Republic of) (IRR)', 'Iraq (IQD)',
    'Ireland (EUR)', 'Isle of Man (GBP)', 'Israel (ILS)', 'Italy (EUR)', 'Ivory Coast (XOF)', 'Jamaica (JMD)',
    'Japan (JPY)', 'Jersey (GBP)', 'Jordan (JOD)', 'Kazakhstan (KZT)', 'Kenya (KES)', 'Kiribati (AUD)',
    'Korea North (KPW)', 'Korea South (KRW)', 'Kuwait (KWD)', 'Kyrgyzstan (KGS)',
    'Lao PeopleÃ•s Democratic Republic (LAK)', 'Laos (LAK)', 'Latvia (LVL)', 'Lebanon (LBP)', 'Lesotho (LSL)',
    'Liberia (LRD)',
    'Libyan Arab Jamahiriya (LYD)', 'Liechtenstein (CHF)', 'Lithuania (LTL)', 'Luxembourg (EUR)', 'Macao S.A.R. (MOP)',
    'Macau (MOP)', 'Macedonia (MKD)', 'Madagascar (MGA)', 'Malawi (MWK)', 'Malaysia (MYR)', 'Maldives (MVR)',
    'Mali (XOF)', 'Malta (MTL)', 'Marshall Islands (USD)', 'Martinique (EUR)', 'Mauritania (MRO)', 'Mauritius (MUR)',
    'Mayotte (EUR)', 'Mexico (MXN)', 'Micronesia Federated States of (USD)', 'Moldova Republic of (MDL)',
    'Monaco (EUR)', 'Mongolia (MNT)', 'Montenegro (EUR)', 'Montserrat (XCD)', 'Morocco (MAD)', 'Mozambique (MZN)',
    'Myanmar (MMK)', 'Namibia (NAD)', 'Nauru (AUD)', 'Nepal (NPR)', 'Netherlands (EUR)',
    'Netherlands Antilles (ANG)', 'New Caledonia (XPF)', 'New Zealand (NZD)', 'Nicaragua (NIO)', 'Niger (XOF)',
    'Nigeria (NGN)', 'Niue (NZD)', 'Norfolk Island (AUD)', 'Northern Mariana Islands (USD)', 'Norway (NOK)',
    'Oman (OMR)', 'Pakistan (PKR)', 'Palau (USD)', 'Palestinian Territory (JOD)', 'Panama (PAB)',
    'Papua New Guinea (PGK)', 'Paraguay (PYG)', 'Peru (PEN)', 'Philippines (PHP)', 'Pitcairn (NZD)', 'Poland (PLN)',
    'Portugal (EUR)', 'Puerto Rico (USD)', 'Qatar (QAR)', 'Reunion (EUR)', 'Romania (RON)', 'Russian Federation (RUB)',
    'Rwanda (RWF)', 'Saint Barthelemy (EUR)', 'Saint Helena (GBP)', 'Saint Kitts (XCD)',
    'Saint Lucia (XCD)', 'Saint Martin (French part) (ANG)', 'Saint Pierre and Miquelon (EUR)',
    'Saint Vincent Grenadines (XCD)', 'Samoa (EUR)', 'San Marino (EUR)', 'Sao Tome and Principe (STD)',
    'Saudi Arabia (SAR)', 'Senegal (XOF)', 'Serbia (RSD)', 'Seychelles (SCR)', 'Sierra Leone (SLL)', 'Singapore (SGD)',
    'Slovakia (Slovak Republic) (SKK)', 'Slovenia (EUR)', 'Solomon Islands (SBD)', 'Somalia (SOS)',
    'South Africa (ZAR)', 'South Georgia and the South Sandwich Islands (GBP)', 'Spain (EUR)', 'Sri Lanka (LKR)',
    'Sudan (SDG)', 'Suriname (SRD)', 'Svalbard and Jan Mayen Islands (NOK)', 'Swaziland (SZL)', 'Sweden (SEK)',
    'Switzerland (CHF)', 'Syrian Arab Republic (SYP)', 'Taiwan (TWD)', 'Tajikistan (TJS)', 'Tanzania (TZS)',
    'Thailand (THB)', 'Togo (XOF)', 'Tokelau (NZD)', 'Tonga (TOP)', 'Trinidad and Tobago (TTD)', 'Tunisia (TND)',
    'Turkey (TRY)', 'Turkmenistan (TMT)', 'Turks and Caicos Islands (USD)', 'Tuvalu (AUD)', 'Uganda (UGX)',
    'Ukraine (UAH)', 'United Arab Emirates (AED)', 'United Kingdom (GBP)', 'United States (USD)',
    'United States Minor Outlying Islands (USD)', 'Uruguay (UYU)', 'US Armed Forces (USD)', 'Uzbekistan (UZS)',
    'Vanuatu (VUV)', 'Vatican City State (Holy See) (EUR)', 'Venezuela (VEF)', 'Vietnam (VND)',
    'Virgin Islands (British) (USD)',
    'Virgin Islands (US) (USD)', 'Wallis and Futuna Islands (XPF)', 'Western Sahara (MAD)', 'Yemen (YER)',
    'Zambia (ZMK)', 'Zimbabwe (ZWD)'
]
